base_url = "./"
title = "Fundación Nodo Ambiental"
description = "FNA Site"

default_language = "es"
generate_feed = true
minify_html = true
output_dir = "../dist/"

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
site_icon = "/icon.png"
site_author = "Ágata Ordano"

[languages.es]
[languages.es.translations]
title = "Fundación Nodo Ambiental"
description = "Sitio web de la Fundación Nodo Ambiental"

[languages.en]
[languages.en.translations]
title = "Fundación Nodo Ambiental"
description = "Sitio web de la Fundación Nodo Ambiental"
